# Generated by Django 3.1.4 on 2020-12-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20201227_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the account', max_length=128)),
                ('bank', models.CharField(help_text='Bank that holds account', max_length=128)),
                ('account_number', models.CharField(help_text='bank acount', max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Avaiable amount', max_digits=64)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the account', max_length=128)),
                ('vat', models.CharField(help_text='VAT number', max_length=128, unique=True)),
                ('business_id', models.CharField(help_text='Company ID number', max_length=128, unique=True)),
                ('account', models.ManyToManyField(related_name='accounts_access', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerBankAccount',
            fields=[
                ('basebankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bank.basebankaccount')),
                ('account', models.ForeignKey(help_text='Account this bank account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to='core.account')),
            ],
            bases=('bank.basebankaccount',),
        ),
        migrations.CreateModel(
            name='ClientBankAccount',
            fields=[
                ('basebankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bank.basebankaccount')),
                ('klient', models.ForeignKey(help_text='Account this bank account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to='bank.clients')),
            ],
            bases=('bank.basebankaccount',),
        ),
    ]
