# Generated by Django 3.1.4 on 2020-12-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201227_1933'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='account',
            field=models.ManyToManyField(related_name='accounts', to='core.Account'),
        ),
    ]
