# Generated by Django 3.1.4 on 2020-12-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201227_1933'),
        ('bank', '0002_auto_20201229_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='account',
        ),
        migrations.AddField(
            model_name='clients',
            name='account',
            field=models.ForeignKey(default=1, help_text='Account this client belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='core.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='business_id',
            field=models.CharField(help_text='Company ID number', max_length=128),
        ),
        migrations.AlterField(
            model_name='clients',
            name='vat',
            field=models.CharField(help_text='VAT number', max_length=128),
        ),
    ]
