# Generated by Django 3.1.4 on 2020-12-26 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The package of permission', max_length=50)),
                ('action', models.CharField(help_text='The action of permission', max_length=50)),
                ('namespace', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Field url namespaces', null=True)),
                ('method', models.CharField(help_text='The action of permission', max_length=50)),
            ],
            options={
                'unique_together': {('name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The package of permission', max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(related_name='group_permisions', to='core.Permission')),
            ],
        ),
    ]
