# Generated by Django 3.1.4 on 2020-12-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_permissiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='namespace',
            field=models.JSONField(blank=True, help_text='Field url namespaces', null=True),
        ),
    ]
