# Generated by Django 3.1.4 on 2020-12-27 00:10

import core.scheme.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201226_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the account', max_length=128)),
                ('vat', models.CharField(help_text='VAT number', max_length=128, unique=True)),
                ('business_id', models.CharField(help_text='Company ID number', max_length=128, unique=True)),
                ('settings', models.JSONField(blank=True, help_text='Account settings in JSON format.', null=True, validators=[core.scheme.validators.validate_account_settings])),
            ],
        ),
    ]
