# Generated by Django 3.1.4 on 2020-12-27 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ManyToManyField(help_text='Account this user belongs to.', related_name='user_accounts', to='core.Account')),
                ('group_permisions', models.ManyToManyField(blank=True, related_name='user_group_permisions', to='core.PermissionGroup')),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_permisions', to='core.Permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
