# Generated by Django 3.1.4 on 2020-12-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_account_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_account_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.ForeignKey(default=1, help_text='Account this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='core.account'),
            preserve_default=False,
        ),
    ]
